### ISSUE TITLE
[Bug]: Issue with icons/colors assigned by I4 using "resistance" or "subtype", maybe others?

### ISSUE THREAD

**Issue by The-Reko** [MissCorruption/QuickLootIE#82]
### What happened? (Actual vs Expected Behavior)

Most of the Icons/Colors in my setup were working correctly, but I would randomly come across some items that seemed like they had the default/incorrect icons/colors, but only in the Quickloot Menu. From what I could tell, it was certain items that were given icons/colors using things like resistances or subtypes rather than keywords.

### What mods for icons where you using, if any?

I4IconAddon/icons.swf

### Steps to Reproduce

Used only the following for testing, nothing else.

_Skyrim 1.5.97
SkyUI
SKSE
BackportedESLSupport
Address Library
I4
I4 1.5 Plugin
Quickloot IE 3.2.0_

I went to qasmoke and went to the All Scrolls container and took the following screenshots:

![QL1](https://github.com/user-attachments/assets/0512b97f-e870-4954-8d65-de2fed6803d8)
![QL2](https://github.com/user-attachments/assets/86e59416-b65b-4171-91bd-4e14671ac805)

As you can see, the colors are there in SkyUI but missing in Quickloot.  I was using a simple Skyrim.json for I4 that only changes the colors for those three scrolls, here's a simple rule for the fire scrolls that will not work for Quickloot:
```
{
      "match": {
        "formType": "Scroll",
        "resistance": "FireResist"
      },
      "assign": {
        "iconColor": "#C73636"
      }
}
```
Another example involing children's toys:

![QL3](https://github.com/user-attachments/assets/3ecd216d-7030-46e9-9995-c8ae976b018f)
![QL4](https://github.com/user-attachments/assets/eb070ea3-4d85-4d28-80fe-829c6c1605b3)

```
{
      "match": {
        "formType": "MiscItem",
        "subType": "Toy"
      },
      "assign": {
        "iconSource": "I4IconAddon/icons.swf",
        "iconLabel": "misc_toy"
      }
}
```

### Version

3.0.0

### What Skyrim version are you using?

1.5.97

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
This is really more @MissCorruption's area of expertise, but taking a quick glance at the [logic for scrolls](https://github.com/MissCorruption/QuickLootIE/blob/master/src/Items/ItemListEntry.cpp#L1000-L1009) it seems like we don't set the `resistance` field at all. Same goes for misc items and `subType`.

**Comment by The-Reko** [comment]
I forgot to mention it, but also potions.  
I looked at the logic you just linked and I'm not seeing `archeType`, for example:

```
{
  "match": {
	  "formType": "Potion",
	  "subType": "Potion",
	  "archetype": "Invisibility"
  },
  "assign": {
	  "subTypeDisplay": "$MagicInvisibility",
	  "iconLabel": "default_potion",
	  "iconColor": "#FFFFFF"
  }
}
```

You also may be missing some values for `actorValue`, for example: Waterbreathing, Waterwalking, Carryweight, MagicResist, PoisonResist possibly more?  Another example:

```
{
  "match": {
	  "formType": "Potion",
	  "subType": "Potion",
	  "archetype": "PeakValueModifier",
	  "actorValue": "CarryWeight"
  },
  "assign": {
	  "subTypeDisplay": "$MagicEnhance",
	  "iconSource": "KIT/Potions.swf",
	  "iconLabel": "potion_square",
	  "iconColor": "#C4CF6B"
  }
}
```

**Comment by MissCorruption** [comment]
I'll take a look at this once I have the chance, ideally I'd want to fix that for 3.3.0. I used values from KIT/AIT to determine what to check, but seems like they don't check for certain things, sorry!

**Comment by AtomCrafty** [comment]
Might be worth going through the SkyUI sources and checking what those set.
https://github.com/schlangster/skyui/blob/master/src/ItemMenus/InventoryDataSetter.as

Apart from that here are some fields set directly by the native ContainerMenu implementation:

```
ItemList__Item::ctor
- text
- count
- equipState
- filterFlag
- favorite
- enabled

InventoryEntryData::PopulateExtraFields
- soulLVL

ContainerMenu::RequestItemCardInfoCallback
- favorite							
- pickpocketChance

EquipmentInfo::SetGFxFlags
- bestInClass

sub_140860C30
- enabled
- equipState

sub_140860A20
- isStealing`
```

**Comment by MissCorruption** [comment]
Closed all reported ones with https://github.com/MissCorruption/QuickLootIE/commit/a4d9f786c0daef6da514a657ca7dc6698114190c, there are things we don't need to check for now like pickpocketChance, though it might be needed for QuickPocket should we do that. bestInClass might be useful once we add the equipping from LootMenu.

**Comment by The-Reko** [comment]
You probably don't want to put "VendorItemTool" at the top of your If statement.  The way it's written it will override the Lockpick icon.  The BYOH Iron Fittings misc item also has both the VendorItemTool keyword and the BYOHHouseCraftingCategorySmithing keyword, so it will have the tool icon instead of the BYOH crafting icon.

**Comment by AtomCrafty** [comment]
Yeah, the order should be the same as in the corresponding SkyUI logic. I think you sorted them by subType id. Btw, you forgot to replace the string "Tool" with its id (8).

**Comment by MissCorruption** [comment]
Good catches, should be all fixed now

**Comment by The-Reko** [comment]
Seems like this has fixed most of my icon issues, well done.  Any other minor discrepancies can be solved by being more specific with the I4 config.

**Comment by The-Reko** [comment]
Sorry to double post, seems like maybe there's still an issue with Arrows and Bolts?  Bolts don't have the correct icon, and i4 can't change the icons for either of them.

**Comment by AtomCrafty** [comment]
Could you post the definition of the rule that fails to match?

**Comment by AtomCrafty** [comment]
Actually, this is a more fundamental issue. The memory layout of `TESAmmo` is different between Flatrim and VR, so CLib disables most of its base classes when cross compiling. That includes `BGSKeywordForm`, so QLIE cannot retrieve keywords for ammo items.

We'll need to do some manual `reinterpret_cast` fuckery here to work around that.

**Comment by AtomCrafty** [comment]
Should be fixed by 770f2413c5b0f4183376e6c67e852396aee9e5b9.

**Comment by The-Reko** [comment]
Issue with
`1570: auto enchantable = skyrim_cast<const BGSKeywordForm*>(item_form);`

should it be
`auto enchantable = skyrim_cast<const TESEnchantableForm*>(item_form);` ?

It compiles after the change, and I'm able to change icons via keywords, however, quickloot isn't properly detecting the subtypes for Ammo, which should be "bolt" and "arrow".

Example:

{
	"match": {
		"formType": "Ammo",
		"subType": "Arrow"
	},
	"assign": {
		"iconSource": "AIT/MoreIcons/icons.swf",
		"iconLabel": "food_stew"
	}
},

This will change all bolt and arrows to the stew icon while

{
	"match": {
		"formType": "Ammo",
		"subType": "Bolt"
	},
	"assign": {
		"iconSource": "AIT/MoreIcons/icons.swf",
		"iconLabel": "food_stew"
	}
},

Will do nothing.  They both work as expected in SkyUI menus.

**Comment by AtomCrafty** [comment]
The commit I posted earlier is out of date. I fixed that copy paste error a couple of hours ago: 79d0626bd8905a92713033ce2e15aff264446abb.

`subType` _should_ also be set correctly, but somehow isn't?
https://github.com/MissCorruption/QuickLootIE/blob/0f2450c88a4f3ae01c928ee32e8f27a674b877da/src/Items/ItemListEntry.cpp#L894
SkyUI code for reference: https://github.com/schlangster/skyui/blob/master/src/ItemMenus/InventoryDataSetter.as#L574-L583
I tested it with the Dwarven Bolt and it shows subType 0, even though it should be a bolt. That must mean CLib's `IsBolt` returns the wrong value, but the IsBolt implementation is identical to the check SkyUI does, so I have no idea why this happens.

Please try using this build of i4 and check the log for what data is actually passed to it.
[InventoryInjector.zip](https://github.com/user-attachments/files/18580243/InventoryInjector.zip)
