### ISSUE TITLE
[Bug]: Dropped weapons stay in loot menu until refresh

### ISSUE THREAD

**Issue by Seb263** [MissCorruption/QuickLootIE#98]
### What happened? (Actual vs Expected Behavior)

Hi,

When using QuickLoot **without USSEP**, killing any NPC with a weapon will cause that weapon (from ExtraDroppedItemList) to show in the loot menu, but after taking it, the item stays visible until:
- you take it a second time
- or look away and back to refresh the UI.

My recent mod, [Death Drop Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/151590), simply restores the vanilla **iDeathDropWeaponChance** setting, which USSEP sets to 0 to avoid issues with generated weapons references that may persists. But the issue still occurs even with no DDO. **Just having USSEP disabled is enough to see it.**

So the bug is native and just hidden by USSEP’s workaround.

Seems like QuickLoot doesn’t update properly when looting items from ExtraDroppedItemList.

Let me know if you want help reproducing or testing.

### Steps to Reproduce

1. **Disable USSEP** (or install [Death Drop Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/151590))
2. Kill any NPC with a weapon
3. Loot via QuickLoot
4. Take the weapon
5. It stays in the list until a UI refresh

### Version

3.0.0

### What Skyrim version are you using?

1.6.1170

### Relevant log output (Expandable)

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sebastien-colin** [comment]
That's good news then. My tests were done with the latest version available on Nexus Mods (3.4.1). I'll let users know that this issue should be resolved in the next major update of QL-IE. Thanks for the response (and for the mod)!

**Comment by AtomCrafty** [comment]
We've had several reports of this still happening with the 4.0 beta build, so I guess I'll have to look into it a bit closer.

**Comment by MissCorruption** [comment]
Could you test the latest [nightly release](https://github.com/MissCorruption/QuickLootIE/releases/tag/Nightly) and see if that fixed your issue? In my testing everything worked fine, but I'd like to get more input on it. Thanks!

**Comment by Seb263** [comment]
Not only does it work, but it also allows you to see more than 2 items from an `ExtraDroppedItemList` (the vanilla inventory interface only displays the first 2 entries of this type).

Looks like this part is **fully functional** now. Great job :)

**Comment by MissCorruption** [comment]
Thanks for the feedback! I'll close this issue then.
